### ISSUE TITLE
download_dataset.sh google drive outdated

### ISSUE THREAD

**Issue by ssktotoro** [catalyst-team/neuro#32]
When running download_dataset.sh the download-gdrive command fails.  If you check the URL generated from the below message you'll see it is invalid.

`bash bin/download_dataset.sh 
--2020-07-31 22:01:34--  https://docs.google.com/uc?export=download&confirm=&id=1M1yYoFU-XlbrP07O01ZKOeP1gZCAl6pd
Resolving docs.google.com (docs.google.com)... 142.250.64.110, 2607:f8b0:4006:807::200e
Connecting to docs.google.com (docs.google.com)|142.250.64.110|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-31 22:01:34 ERROR 404: Not Found.`

**Comment by Scitator** [comment]
Hi,
You are right, something went wrong with link, thanks for you issue 👍
Could you please try `download-gdrive 1cD0euGOhuOm8w-XXa7b4wQeZ_RfkmxN4 brain_data.zip`?

**Comment by ssktotoro** [comment]
This works.  do you want me to open up a quick PR to fix?

**Comment by Scitator** [comment]
Not sure yet :)
Could you please check the pipeline first? It's our previous data version and I am not yet sure on full pipeline correctness with it. Nevertheless, I don't know where new data is :) (al least for now)

**Comment by ssktotoro** [comment]
Opening a PR with the full pipeline running.
